### ISSUE TITLE
Starting server fails - DB[1] exec() near "STRICT": syntax error

### ISSUE THREAD

**Issue by rhclayto** [GrapheneOS/AttestationServer#138]
Following the installation instructions, after running `./deploy-server`, I check `systemctl status attestation` & find the service has failed with the following error log:

```java

Dec 22, 2021 4:13:22 PM com.almworks.sqlite4java.Internal log
INFO: [sqlite] DB[1]: instantiated [samples.db]
Dec 22, 2021 4:13:22 PM com.almworks.sqlite4java.Internal log
INFO: [sqlite] Internal: loaded sqlite4java-linux-amd64-1.0.392 from system path
Dec 22, 2021 4:13:22 PM com.almworks.sqlite4java.Internal log
INFO: [sqlite] Internal: loaded sqlite 3.8.7, wrapper 1.3
Dec 22, 2021 4:13:22 PM com.almworks.sqlite4java.Internal log
INFO: [sqlite] DB[1]: opened
Dec 22, 2021 4:13:22 PM app.attestation.server.AttestationServer getUserVersion
INFO: Existing schema version: 1
Dec 22, 2021 4:13:22 PM com.almworks.sqlite4java.Internal log
INFO: [sqlite] DB[1]: connection closed
Exception in thread "main" com.almworks.sqlite4java.SQLiteException: [1] DB[1] exec() near "STRICT": syntax error
        at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1436)
        at com.almworks.sqlite4java.SQLiteConnection.exec(SQLiteConnection.java:496)
        at app.attestation.server.AttestationServer.createSamplesTable(AttestationServer.java:210)
        at app.attestation.server.AttestationServer.main(AttestationServer.java:245)

```

Any clues?

**Comment by rhclayto** [comment]
I had to compile https://github.com/GrapheneOS/sqlite4java for my version of glibc/libc6. Now it works.

**Comment by thestinger** [comment]
I built it on Arch Linux and glibc isn't forwards compatible with new versions of glibc, only backwards compatible, unlike how it works on Android where it goes both ways and they expect you to always build with the latest version.
